# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Astro-SIMBAD
version:      2.0.0
version_from: SIMBAD.pm
installdirs:  site
requires:
    HTML::Parser:                  3.36
    HTML::Tree:                    3.17
    LWP:                           5.53

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
